project_id = "gpiecetkpckiqndyyohf"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["present://auth/confirm", "present://invite/**", "http://localhost:3000/**", "https://goncalopina-del.github.io/LessPhone/**"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false

[auth.external.apple]
enabled = true
client_id = "app.present.ios"

[auth.external.google]
enabled = true
client_id = "app.present.android"

[functions.create-family-invite]
verify_jwt = true

[functions.process-session-end]
verify_jwt = true

[functions.send-nudge-notification]
verify_jwt = true

[analytics]
enabled = false
